<?php
// Style
$this->form->setAttribute('class', 'form-horizontal');
// We call the prepare here in order to fill the initial data and adjust the form properties, if needed.
$this->form->prepare();

echo $this->form()->openTag($this->form);
echo '<fieldset>';

foreach ($this->form as $element) {
    if (!($element instanceof Zend\Form\Element\Submit)) {
?>
    <div class="control-group">
      <label class="control-label" for="<?= $element->getName() ?>"><?= $element->getLabel() ?></label>
        <div class="controls">
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
    } else {
        $element->setAttribute('class', 'btn btn-primary');
?>
        <div class="form-action">
          <?= $this->formElement($element) ?>
        </div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();
?>
