 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums'; // Set the title for the page
 $this->headTitle($title); // Set the title for the <head> section using the headTitle() view helper - which will display in the browser's title bar. 
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a> <!-- We then craete a link to add a new album. -->
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td>
         <!-- 
            The url view helper is provided by ZF2 and is used to create the 
            links we need. The first parameter to url() is the route name we wish 
            to use for contruction of the URL, and the second parameter is an array 
            of all the variables to fit into the placeholders to use. In this case 
            we use our 'album' route which is set up to accept two placeholder 
            variables: action and id. 
         -->
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>